version: '3.9'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    tty: true
    stdin_open: true
    ports:
      - 5003:5003
