version: "3.1"

services: 
  db:
    image: postgres:11.5
    container_name: "velog_db"
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./docker/data:/var/lib/postgresql/data
  