name: Run Velog Server test

on:
  push:
    branches: ["main"]
    paths:
      - "packages/velog-server/**"
  pull_request:
    branches: ["main"]
    paths:
      - "packages/velog-server/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./packages/velog-server"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16
          cache: "pnpm"
          cache-dependency-path: "./packages/velog-server/pnpm-lock.yaml"

      - run: pnpm install

      - name: Check tsc version
        run: tsc --version

      - name: Build
        run: pnpm build

      - name: Run Tests
        run: pnpm test
