name: Run Velog Server test

on:
  push:
    branches: ["main"]
    paths:
      - "packages/velog-server/**"
  pull_request:
    branches: ["main"]
    paths:
      - "packages/velog-server/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm

      - name: Install Dependencies
        run: cd packages/velog-server && pnpm install

      - name: Build
        run: cd packages/velog-server && pnpm build

      - name: Run Tests
        run: cd packages/velog-server && pnpm test
